Repository ManageIQ/inventory_refresh, pull requests merged in 2018-10, with the labels that each got.

#28 Replace ampersand with try in persister's add_collection
  lib/inventory_refresh/persister.rb
Labels: bug

#26 TestBasePersister and TestBuilder moved to spec Helpers
  spec/helpers/test_base_persister.rb
  spec/helpers/test_builder.rb
  spec/helpers/test_builder/cloud_manager.rb
  spec/helpers/test_builder/network_manager.rb
  spec/helpers/test_builder/persister_helper.rb
  spec/helpers/test_builder/shared.rb
  spec/save_inventory/acyclic_graph_of_inventory_collections_spec.rb
  spec/save_inventory/graph_of_inventory_collections_spec.rb
  spec/save_inventory/init_data_helper.rb
  spec/save_inventory/single_inventory_collection_spec.rb
Labels: test

#30 Add a .from_hash method to Persister
  lib/inventory_refresh/persister.rb
  spec/helpers/test_persister.rb
  spec/persister/serializing_spec.rb
  spec/persister/test_collector.rb
Labels: enhancement

#31 Remove unused concurrent_safe strategy
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/save_collection/base.rb
  lib/inventory_refresh/save_collection/saver/concurrent_safe.rb
Labels: cleanup

#32 Relax version requirements on rails/pg gems
  inventory_refresh.gemspec
Labels: enhancement

#33 Increasing test coverage for persister
  lib/inventory_refresh/inventory_collection/builder.rb
  spec/persister/builder_spec.rb
  spec/persister/persister_spec.rb
Labels: refactoring, test

#35 InventoryCollection refactoring
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers.rb
  lib/inventory_refresh/inventory_collection/helpers/associations_helper.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
  lib/inventory_refresh/inventory_collection/helpers/questions_helper.rb
  lib/inventory_refresh/inventory_collection/index/type/skeletal.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  lib/inventory_refresh/save_collection/saver/concurrent_safe_batch.rb
  spec/persister/builder_spec.rb
  spec/persister/finders_spec.rb
Labels: refactoring

#38 Fix creating complement_of! query for single manager_uuid
  lib/inventory_refresh/save_collection/saver/sql_helper.rb
  spec/persister/retention_strategies_spec.rb
Labels: bug

#36 Skip processing of noop earlier
  lib/inventory_refresh/save_collection/base.rb
Labels: enhancement

#37 Delete complement only active records
  lib/inventory_refresh/save_collection/saver/sql_helper.rb
Labels: enhancement
