Repository ManageIQ/inventory_refresh, pull requests merged in 2019-01, with the labels that each got.

#60 Add a flag to check and assert graph integrity
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
  lib/inventory_refresh/inventory_collection/index/proxy.rb
  lib/inventory_refresh/persister.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  spec/helpers/test_persister.rb
  spec/helpers/test_persister/cloud.rb
  spec/helpers/test_persister/containers.rb
Labels: technical debt

#62 Merge pull request #60 from agrare/add_graph_integrity_check_flag
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/index/proxy.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  spec/save_inventory/acyclic_graph_of_inventory_collections_spec.rb
Labels: bug, technical debt

#63 Change FactoryGirl to FactoryBot
  .travis.yml
  inventory_refresh.gemspec
  spec/factories/authentication.rb
  spec/factories/availability_zone.rb
  spec/factories/cloud_tenants.rb
  spec/factories/container_group.rb
  spec/factories/container_image.rb
  spec/factories/container_image_registry.rb
  spec/factories/container_nodes.rb
  spec/factories/container_project.rb
  spec/factories/container_replicator.rb
  spec/factories/containers.rb
  spec/factories/disk.rb
  spec/factories/event_stream.rb
  spec/factories/ext_management_system.rb
  spec/factories/flavor.rb
  spec/factories/hardware.rb
  spec/factories/host.rb
  spec/factories/nested_containers.rb
  spec/factories/network.rb
  spec/factories/network_port.rb
  spec/factories/orchestration_stack.rb
  spec/factories/orchestration_stack_resource.rb
  spec/factories/physical_server.rb
  spec/factories/service.rb
  spec/factories/source_region.rb
  spec/factories/subscription.rb
  spec/factories/vm_or_template.rb
  spec/helpers/spec_mocked_data.rb
  spec/persister/finders_spec.rb
  spec/persister/local_db_finders_spec.rb
  spec/persister/parallel_saving_spec.rb
  spec/persister/retention_strategies_spec.rb
  spec/persister/serializing_spec.rb
  spec/persister/skeletal_precreate_spec.rb
  spec/persister/sweep_inactive_records_spec.rb
  spec/persister/unconnected_edges_spec.rb
  spec/save_inventory/acyclic_graph_of_inventory_collections_spec.rb
  spec/save_inventory/build_parent_inventory_collections_spec.rb
  spec/save_inventory/graph_of_inventory_collections_spec.rb
  spec/save_inventory/graph_of_inventory_collections_targeted_refresh_spec.rb
  spec/save_inventory/saver_strategies_spec.rb
  spec/save_inventory/single_inventory_collection_spec.rb
  spec/save_inventory/strategies_and_references_spec.rb
  spec/support/factory_bot_helper.rb
  spec/target_collection_spec.rb
  spec/target_spec.rb
Labels: test
