Repository ManageIQ/inventory_refresh, pull requests merged in 2019-04, with the labels that each got.

#69 Remove all manager uuids and delete complement strategy
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
  lib/inventory_refresh/inventory_collection/helpers/questions_helper.rb
  lib/inventory_refresh/inventory_collection/scanner.rb
  lib/inventory_refresh/inventory_collection/serialization.rb
  lib/inventory_refresh/persister.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  lib/inventory_refresh/save_collection/saver/retention_helper.rb
  lib/inventory_refresh/save_collection/saver/sql_helper.rb
  spec/persister/retention_strategies_spec.rb
  spec/save_inventory/single_inventory_collection_spec.rb
Labels: cleanup, refactoring

#71 Remove parent inventory collections concept
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
  lib/inventory_refresh/inventory_collection/helpers/questions_helper.rb
  lib/inventory_refresh/inventory_collection/scanner.rb
  spec/helpers/test_builder/cloud_manager.rb
  spec/helpers/test_builder/shared.rb
  spec/helpers/test_persister/containers.rb
  spec/persister/retention_strategies_spec.rb
  spec/persister/sweep_inactive_records_spec.rb
  spec/save_inventory/acyclic_graph_of_inventory_collections_spec.rb
  spec/save_inventory/build_parent_inventory_collections_spec.rb
  spec/save_inventory/single_inventory_collection_spec.rb
  spec/save_inventory/strategies_and_references_spec.rb
Labels: cleanup, performance, refactoring

#72 Remove extra queries to source related tables
  lib/inventory_refresh/save_collection/saver/base.rb
  spec/save_inventory/acyclic_graph_of_inventory_collections_spec.rb
  spec/save_inventory/single_inventory_collection_spec.rb
Labels: enhancement, performance

#73 Remove targeted arel option
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
Labels: cleanup

#74 Fix rspec factory bot warnings
  spec/factories/hardware.rb
  spec/factories/host.rb
  spec/factories/orchestration_stack.rb
  spec/factories/physical_server.rb
  spec/factories/vm_or_template.rb
Labels: cleanup

#75 Remove targeted option
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/inventory_collection/builder.rb
  lib/inventory_refresh/inventory_collection/helpers/initialize_helper.rb
  lib/inventory_refresh/inventory_collection/helpers/questions_helper.rb
  lib/inventory_refresh/inventory_collection/scanner.rb
  lib/inventory_refresh/inventory_object_lazy.rb
  lib/inventory_refresh/persister.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  lib/inventory_refresh/save_collection/saver/concurrent_safe_batch.rb
  spec/helpers/test_persister/cloud.rb
  spec/helpers/test_persister/containers.rb
  spec/persister/builder_spec.rb
  spec/save_inventory/saver_strategies_spec.rb
  spec/save_inventory/single_inventory_collection_spec.rb
  spec/save_inventory/strategies_and_references_spec.rb
  spec/schema.rb
Labels: cleanup

#76 Simplify the records iterator
  lib/inventory_refresh/application_record_iterator.rb
  lib/inventory_refresh/inventory_collection.rb
  lib/inventory_refresh/save_collection/saver/base.rb
  lib/inventory_refresh/save_collection/saver/concurrent_safe_batch.rb
  lib/inventory_refresh/save_collection/saver/partial_upsert_helper.rb
  spec/persister/parallel_saving_spec.rb
  spec/persister/sweep_inactive_records_spec.rb
  spec/persister/test_collector.rb
Labels: enhancement, performance

#80 Update to not log ems.name
  lib/inventory_refresh/save_collection/base.rb
  lib/inventory_refresh/save_collection/topological_sort.rb
  lib/inventory_refresh/save_inventory.rb
  spec/persister/parallel_saving_spec.rb
  spec/persister/test_collector.rb
Labels: enhancement
