Repository ManageIQ/inventory_refresh, pull requests merged in 2022-02, with the labels that each got.

#100 Remove Hakiri
  README.md
Labels: cleanup, developer

#105 Fix GHA yaml syntax
  .github/workflows/ci.yaml
Labels: bug, test

#106 Switch to bundler-inject from custom bundler.d handling
  Gemfile
Labels: enhancement, developer

#103 Allow Rails 6.1
  .github/workflows/ci.yaml
  Gemfile
  inventory_refresh.gemspec
Labels: dependencies

#107 Fix missing returns on cached values
  lib/inventory_refresh/inventory_collection.rb
Labels: bug

#108 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer
